# name of the workflow
name: DEMO-FIRST-WF

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello
        run: echo "Hello, world!"

      - name: Print current date
        run: date

      - name: Node version
        run: node --version

      - name: Display secrets
        run: |
          echo "GITHUB_TOKEN: ${{ secrets.DEMO_TOKEN }}"
